export default [
  {
    title:"01 - Atomico (FNR Exclusive version)",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "1.mp3",
  },
  {
    title:"02 - Energetico (Intro Xtended Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "2.mp3",
  },
  {
    title:"03 - I wanna rock",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "3.mp3",
  },
  {
    title:"04 - Get On The Floor Part II (Flash Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "4.mp3",
  },
  {
    title:"05 - Good 4 me",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "5.mp3",
  },
  {
    title:"06 - Boogie Shakes",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "6.mp3",
  },
  {
    title:"07 - Hey Mr. DJ (Make my body move)",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "7.mp3",
  },
  {
    title:"08 - Ready 2 House",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "8.mp3",
  },
  {
    title:"09 - House Music Was Born",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "9.mp3",
  },
  {
    title:"10 - Comin' Crazy",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "10.mp3",
  },
  {
    title:"11 - Chicago is a noise",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "11.mp3",
  },
  {
    title:"12 - Bat Case",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "12.mp3",
  },
  {
    title:"13 - I Need To Know",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "13.mp3",
  },
  {
    title:"14 - Party On Marmion",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "14.mp3",
  },
  {
    title:"15 - Tell Me",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "15.mp3",
  },
  {
    title:"16 - Bump That Beat",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "16.mp3",
  },
  {
    title:"17 - C'mon Everybody",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "17.mp3",
  },
  {
    title:"18 - Energetico (NRG Maxi Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "18.mp3",
  },
  {
    title:"19 - Hey DJ!!",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "19.mp3",
  },
  {
    title:"20 - Vamonos' 99",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "20.mp3",
  },
];
