export default [
  {
    title:"01 - Atomico (FNR Exclusive version)",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "atomico.mp3",
  },
  {
    title:"02 - Energetico (Intro Xtended Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"I wanna rock",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"Get On The Floor Part II (Flash Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"Good 4 me",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: ".mp3",
  },
  {
    title:"",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: ".mp3",
  },
];
