export default [
  {
    title:"01 - Atomico (FNR Exclusive version)",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "1.mp3",
  },
  {
    title:"02 - Energetico (Intro Xtended Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "2.mp3",
  },
  {
    title:"I wanna rock",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "3.mp3",
  },
  {
    title:"Get On The Floor Part II (Flash Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "4.mp3",
  },
  {
    title:"Good 4 me",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "5.mp3",
  },
  {
    title:"Boogie Shakes",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "6.mp3",
  },
  {
    title:"Hey Mr. DJ (Make my body move)",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "7.mp3",
  },
  {
    title:"Ready 2 House",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "8.mp3",
  },
  {
    title:"House Music Was Born",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "9.mp3",
  },
  {
    title:"Comin' Crazy",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "10.mp3",
  },
  {
    title:"Chicago is a noise",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "11.mp3",
  },
  {
    title:"Bat Case",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "12.mp3",
  },
  {
    title:"I Need To Know",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "13.mp3",
  },
  {
    title:"Party On Marmion",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "14.mp3",
  },
  {
    title:"Tell Me",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "15.mp3",
  },
  {
    title:"Bump That Beat",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "16.mp3",
  },
  {
    title:"C'mon Everybody",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "17.mp3",
  },
  {
    title:"Energetico (NRG Maxi Mix)",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "18.mp3",
  },
  {
    title:"Hey DJ!!",
    artist: "Nedu Lopes",
    cover: "img.jpg",
    file: "19.mp3",
  },
  {
    title:"Vamonos' 99",
    artist: "Denys Victoriano",
    cover: "img.jpg",
    file: "20.mp3",
  },
];
